apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sugarshops.swat.sz
spec:
  group: swat.sz
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                machineImage:
                  type: string
                  default: "nginx"
                port:
                  type: string
  conversion:
    strategy: None
  scope: Namespaced
  names:
    plural: sugarshops
    singular: sugarshop
    kind: sugarshop
    shortNames:
    - sgsp
    - sgs


