apiVersion: v1
kind: Pod
metadata:
  name: sugar
spec:
  containers:
  - name: sugar-container
    image: nginx
    env:
      - name: MY_ENV_VARIABLE
    volumeMounts:
      - name: sugarvolume
        mountPath: /data
  volumes:
    - name: sugarvolume
      persistentVolumeClaim:
        claimName: pvc-sugar