
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.julian.swat
  resources:
  - sugarshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.julian.swat
  resources:
  - sugarshops/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.julian.swat
  resources:
  - sugarshops/status
  verbs:
  - get
  - patch
  - update
